Style/Documentation:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrailingBlankLines:
  Enabled: false

Style/SpaceInsideStringInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
